name: CI
on: [push, pull_request]
jobs:
  build:
    name: Run Build
    runs-on: ubuntu-latest
    steps:
      - name: build
        if: ${{!contains(github.event.pull_request.labels.*.name, 'documentation')}}
        run: yarn build
