name: CI
on:
  pull_request:
    branches: ["**"]
    types: [opened, synchronize, reopened, edited, labeled, unlabeled]
  push:
    branches: ["**"]
jobs:
  build:
    name: Run Build
    runs-on: ubuntu-latest
    steps:
      - name: build
        if: ${{github.event_name == 'pull_request' && !contains(github.event.pull_request.labels.*.name, 'documentation')}}
        run: |
          yarn build
