name: CI
on:
  pull_request:
    branches: ["**"]
  push:
    branches: ["**"]
jobs:
  build:
    name: Run Build
    runs-on: ubuntu-latest
    steps:
      - name: build
        if: ${{ github.event_name == 'pull_request'}} && ${{ github.event.label.name != 'documentation' }}
        run: yarn build
